### PR TITLE
Fork branch

### PR DESCRIPTION
**Pull request by Sirokujira**
Build support in Windows environment
Reference example of official website Partial implementation
Adding automatic test configuration file

### CODE REVIEW

**Comment by mys007** [comment]
Hi @Sirokujira, that's a terrific extension, also in terms of all newly wrapped modules! It seems to me that this original project is dormant/abandoned, do you perhaps want to open your repository for full use as heir (I think your fork is the most advanced one), e.g. allowing to post issues to your code? Because I just found one: In `pxi/PointCloud_PointXYZI.pxi#L158` you are casting intensity to integer, while the underlying type is float, so in fact float intensity is not supported. I suppose you wanted to support labels, but there is `pcl::PointXYZL` for that...

**Comment by Sirokujira** [comment]
Whether you are going to create an original project
→ Since the original has stopped at 1.6 base, I am considering reimplementing on 1.7 / 1.8 basis.
    (Due to the large difference between 1.6 and 1.7)
    (The number of parts that can be simplified as a code due to the version of Cython going up has increased)

However, if you create a project as original
Because there is a possibility that it becomes correspondence by an individual,
I want to make it a situation where many people manage.
(Preferably I would like the official side to have a repository ...)

In addition, it is necessary to think about the module name.
(Since there is already a module named "pypcl")

**Comment by mys007** [comment]
Or perhaps you could write to straw@bio.uni-freiburg.de so that they add you as project-owner?

**Comment by ahundt** [comment]
@strawlab @astraw @hdorothea Could you consider allowing @Sirokujira to become a maintainer of this repository? It seems like he has been doing a good job maintaining it over the last couple of years.

https://github.com/Sirokujira/python-pcl/tree/1.7_to_1.9

@Sirokujira If you don't hear from the authors, might I suggest taking the approach taken by https://github.com/python-pillow/Pillow/ in the same situation, where they created a new repository with a new name so it is searchable because forks are not searchable, crediting the original authors for their work and yourself as the maintainer? It is possible that the pcl authors would allow you to create it on their organization page https://github.com/PointCloudLibrary. The license is consistent so that aspect should be good to go.

**Comment by astraw** [comment]
@ahundt Thanks for the mention -- not sure why, but I wasn't getting notified on this. I just sent an invite to @Sirokujira to join the repo.

@Sirokujira you are welcome to merge as you see fit, release updates under the current name and to update the master branch.

@nzjrs I presume you are OK with all this. I don't see any commits from you since February 2016.

**Comment by Sirokujira** [comment]
@astraw
I confirmed the receipt of the invitation and approved it.
Thank you for inviting me.

I'd like to confirm, but can I use an external test CI (Appveyor / Travis CI) for the current repository?
(Since it is a check as to whether merge items can be successfully built)

If you do not have a test environment, I would like to ask for cooperation with the above test environment.
(Since the configuration file has already been written, if only Appobeyor / Travis CI linkage is done, test execution is possible.)

**Comment by astraw** [comment]
@Sirokujira OK to use external test CI - let me know if I need to do anything to set it up, but you should be able to.

**Comment by Sirokujira** [comment]
@astraw 

Regarding Travis CI,

It seems that there is synchronization between accounts
I set up the setting with my account.

Could you just check whether strawlab / python-pcl is checked?


Regarding AppVeyor,

Go to https://ci.appveyor.com and add an account.
Move to https://ci.appveyor.com after adding.
When you click New Project
Since the list of Github's Repogitry items is displayed
Select it and add it as a test item.

With the current Appveyor account
It seems that you can test strawlab / python-pcl's repository
In the meantime I will use my account to test.

**Comment by astraw** [comment]
Regarding Travis CI: there is https://travis-ci.org/Sirokujira/python-pcl and https://travis-ci.org/strawlab/python-pcl . The strawlab version is for this repository. I just created https://ci.appveyor.com/project/astraw/python-pcl .

Please let me know if this works and if you need more.

**Comment by Sirokujira** [comment]
@astraw 
Thank you for confirmation.
That’s all.
That is absolutely fine.
Thank you very much.

**Comment by ahundt** [comment]
Cool! Perhaps it might make sense to tag a release as well?

**Pull request merged**
