### PR TITLE
Fix failing test because of wrong attribute name

### PR DESCRIPTION
**Pull request by ccordoba12**
I discovered this error while running the test suite.

### CODE REVIEW

**Comment by nzjrs** [comment]
Thanks!

**Comment by ccordoba12** [comment]
@nzjrs, you're welcome!

I have a quick question while you're around: has somebody been able to run `python-pcl` on Windows? I'm getting segfaults with almost all tests...

**Comment by nzjrs** [comment]
I have no idea if people have run it successfully on windows sorry. We use Linux only in our research group.

**Comment by ccordoba12** [comment]
Ok, thanks for the info :-)

**Pull request merged**
