### PR TITLE
Installation for PCL 1.10.0, python3.8-venv on Ubuntu 20.04

### PR DESCRIPTION
**Pull request by marcelbrucker**
These changes allowed me to install [python-pcl](https://github.com/strawlab/python-pcl/) using the newest PCL version (`sudo apt install libpcl-dev`) and import after applying this [fix](https://github.com/strawlab/python-pcl/issues/71#issuecomment-289805368).

1. `git clone https://github.com/marcelbrucker/python-pcl.git`
2. `cd python-pcl/`
3. `python setup.py install`

Screenshot from 2022-04-17 09-29-51

---
This change is [Reviewable](https://reviewable.io/reviews/strawlab/python-pcl/407)

### CODE REVIEW

**Comment by marcelbrucker** [comment]
Ran into the problem: `AttributeError: module 'pcl' has no attribute 'PointCloud'` and eventually solved it by using v0.2.0 instead of v0.3.0 from my forked repo as explained [here](https://github.com/strawlab/python-pcl/issues/320#issuecomment-799986976) but with the same changes.

**Comment by Petros626** [comment]
@ marcelbrucker Hey,

could you help me with installation on Ubuntu 20.04, Python 3.8.10? I tried your suggestions and from @mrinalsenapati04.

**Comment by marcelbrucker** [comment]
> @marcelbrucker Hey,
> 
> could you help me with installation on Ubuntu 20.04, Python 3.8.10? I tried your suggestions and from @mrinalsenapati04.

Where exactly are you stuck? 
You have to use the ZIP file from [here](https://github.com/strawlab/python-pcl/releases/tag/v0.2.0), make similar adjustments than the ones I did in this pull request and finally install from source by `python setup.py install`.

**Comment by Petros626** [comment]
> > @marcelbrucker Hey,
> > could you help me with installation on Ubuntu 20.04, Python 3.8.10? I tried your suggestions and from @mrinalsenapati04.
> 
> Where exactly are you stuck? You have to use the ZIP file from [here](https://github.com/strawlab/python-pcl/releases/tag/v0.2.0), make similar adjustments than the ones I did in this pull request and finally install from source by `python setup.py install`.

yes exactly I did these steps and the installation finished successfully, but I try to use PCL via VS Code. So I have updated the PATHS in the provided .json file, but the functions for example pcl::StatisticalOutlierRemoval (I know it's C++), which are given in Introduction are inaccessible.

**Comment by marcelbrucker** [comment]
> StatisticalOutlierRemoval

Screenshot from 2022-05-14 07-47-11

It's likely that IntelliSense does not work properly but still you should be able to use the functions.
Can't you replicate for instance these lines without errors?

**Comment by yiyeChen** [comment]
@marcelbrucker 

Hey, can you push your modified v0.2.0 to your forked repo? I tried to modify the setup.py but resulted in errors. Thanks

**Comment by Petros626** [comment]
Yes maybe that's the reason, but I added all the paths to the PCL library, so IntelliSense should found them. Here the requested commands:

Screenshot from 2022-05-15 09-39-06

I don't get it why, it's not working with VS Code, could you help there?

**Comment by marcelbrucker** [comment]
> @marcelbrucker
> 
> Hey, can you push your modified v0.2.0 to your forked repo? I tried to modify the setup.py but resulted in errors. Thanks

I made a new commit.

**Comment by Petros626** [comment]
@marcelbrucker it`s working now, I only installed the way you recommended and set the paths in my .json file in VS Code

**Comment by seungchan-mok** [comment]
@marcelbrucker Can u push your pip freeze file? or can u notify me specific version of requirements? Thank you in advance.

**Comment by marcelbrucker** [comment]
> @marcelbrucker Can u push your pip freeze file? or can u notify me specific version of requirements? Thank you in advance.

As far as I know there are none. Can you not install?

**Comment by bastikohn** [comment]
> Ran into the problem: `AttributeError: module 'pcl' has no attribute 'PointCloud'` and eventually solved it by using v0.2.0 instead of v0.3.0 from my forked repo as explained [here](https://github.com/strawlab/python-pcl/issues/320#issuecomment-799986976) but with the same changes.

I just had a look at this pull request and I believe the first commit [#0227ad](https://github.com/strawlab/python-pcl/pull/407/commits/0227ad2a9b6ade2d25e2535d1346bda0df7f13e4) is working on its own. The commit afterwards (ironically named "Import now works") breaks the import for me. Most of this library's code is natively linked into a library named _pcl, that gets imported into python using `from ._pcl import *`. By changing this to `from pcl import *`, this library will not get loaded at all, which likely causes the `AttributeError` as `PointCloud` is defined within this library.
Thus, to fix this issue, it should be sufficient to revert the two latest commits (downgrade is not necessary anymore, I suppose). Hope this helps!

**Comment by AxeBlue** [comment]
> Ran into the problem: `AttributeError: module 'pcl' has no attribute 'PointCloud'` and eventually solved it by using v0.2.0 instead of v0.3.0 from my forked repo as explained [here](https://github.com/strawlab/python-pcl/issues/320#issuecomment-799986976) but with the same changes.
Hi, in python3.6, there is still the problem......
image

**Review by sumeshthakr — APPROVED** [review]

**Comment by callzhang** [comment]
Any updates? Still no luck:
```bash
$ python
Python 3.8.12 (default, Oct 12 2021, 13:49:34) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pcl
>>> pcl.load
<function load at 0x7fa40b0b2ca0>
>>> pcl.PointCloud
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'pcl' has no attribute 'PointCloud'
>>> pcl.PointCloud()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'pcl' has no attribute 'PointCloud'
>>> 
```

**Comment by estrellademaralex** [comment]
I'm facing the same problem, are there any updates?

`Python 3.8.10 (default, Jun  2 2021, 10:49:15) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pcl
>>> pcl.PointCloud
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'pcl' has no attribute 'PointCloud'
>>> 
`

Thanks

**Comment by Petros626** [comment]
> I'm facing the same problem, are there any updates? root@roblearn:~# python3 Python 3.8.10 (default, Jun 2 2021, 10:49:15) [GCC 9.4.0] on linux Type "help", "copyright", "credits" or "license" for more information.
> 
> > > > import pcl
> > > > pcl.PointCloud
> > > > Traceback (most recent call last):
> > > > File "", line 1, in 
> > > > AttributeError: module 'pcl' has no attribute 'PointCloud'
> 
> Thanks

In which IDE you're using the `pcl` library?

**Comment by estrellademaralex** [comment]
> > I'm facing the same problem, are there any updates? root@roblearn:~# python3 Python 3.8.10 (default, Jun 2 2021, 10:49:15) [GCC 9.4.0] on linux Type "help", "copyright", "credits" or "license" for more information.
> > > > > import pcl
> > > > > pcl.PointCloud
> > > > > Traceback (most recent call last):
> > > > > File "", line 1, in
> > > > > AttributeError: module 'pcl' has no attribute 'PointCloud'
> > 
> > 
> > Thanks
> 
> In which IDE you're using the `pcl` library?

I'm not using any IDE. I installed pcl library with 'apt install libpcl-dev'
The installation is located here:
Screenshot from 2023-10-18 18-19-18

**Comment by Petros626** [comment]
> > > I'm facing the same problem, are there any updates? root@roblearn:~# python3 Python 3.8.10 (default, Jun 2 2021, 10:49:15) [GCC 9.4.0] on linux Type "help", "copyright", "credits" or "license" for more information.
> > > > > > import pcl
> > > > > > pcl.PointCloud
> > > > > > Traceback (most recent call last):
> > > > > > File "", line 1, in
> > > > > > AttributeError: module 'pcl' has no attribute 'PointCloud'
> > > 
> > > 
> > > Thanks
> > 
> > 
> > In which IDE you're using the `pcl` library?
> 
> I'm not using any IDE. I installed pcl library with 'apt install libpcl-dev' The installation is located here: Screenshot from 2023-10-18 18-19-18

Please use this formatter for code
```c
Some code or text 

When you try to call a function you get the message that it can't find the module? 
```

**Comment by estrellademaralex** [comment]
> > > > I'm facing the same problem, are there any updates? root@roblearn:~# python3 Python 3.8.10 (default, Jun 2 2021, 10:49:15) [GCC 9.4.0] on linux Type "help", "copyright", "credits" or "license" for more information.
> > > > > > > import pcl
> > > > > > > pcl.PointCloud
> > > > > > > Traceback (most recent call last):
> > > > > > > File "", line 1, in
> > > > > > > AttributeError: module 'pcl' has no attribute 'PointCloud'
> > > > 
> > > > 
> > > > Thanks
> > > 
> > > 
> > > In which IDE you're using the `pcl` library?
> > 
> > 
> > I'm not using any IDE. I installed pcl library with 'apt install libpcl-dev' The installation is located here: Screenshot from 2023-10-18 18-19-18
> 
> Please use this formatter for code
> 
> ```c
> Some code or text 
> 
> When you try to call a function you get the message that it can't find the module? 
> ```

The only available functions that I have are load and save. 
The ones that are on the __init__.py file

**Comment by Petros626** [comment]
use the quote reply only if you want to, when you refer to a comment. So maybe you can add the functions to `__init__.py` to call `pcl.PointCloud`

**Comment by Petros626** [comment]
@estrellademaralex 
I remember, that I installed it locally to work for me, but which version I don't no...
I have no access to this notebook anymore, so I would try to search for python dont recognize package or smth. like that. I only installed it from source and paste the path in `VS Code` to find the libs and the functions.

**Comment by AdonaiVera** [comment]
Thank you for your contribution, @marcelbrucker  . We greatly appreciate your support and would like to continue working with you on this amazing project.
You can join the discord channel https://discord.gg/Zjy6ueqM7Z

**Pull request merged**
