### PR TITLE
add possibility to use PCL-1.8

### PR DESCRIPTION
**Pull request by toinsson**

### CODE REVIEW

**Comment by LovelyHorse** [comment]
I made this change to my local version with no issues; running fine with python 3.5 also.

**Comment by funsim** [comment]
Works fine for me also

**Comment by Ziul** [comment]
Also confirm this work. Python3 support confirmed.

**Comment by leaveitout** [comment]
Me too, python 3.

**Comment by Sirokujira** [comment]
Acknowledged
 "Fork Branch" #106

**Pull request closed without merging**
